### ISSUE TITLE
Installation by cloning from git stringr is missing.

### ISSUE THREAD

**Issue by snsb-seifert** [AgentschapPlantentuinMeise/MIDSCalculator#63]
When installing teh app by cloning the repo in a clean rstudio docker the library stringr is not installed automatically.

**Setup:**
Docker image: rocker/rstudio 8319c72d79f0
clone app from git as new RStudio project
install shiny package
run app.R

**result:** 
App will start,
browser is opend
page is grayed out
RStudio console shows errors the stringr package is not found
`Error in library(stringr) : there is no package called ‘stringr’`

**fix**
stop app
install.packages('stringr')
rerun app

**Comment by matdillen** [comment]
I added `stringr` to the packages list. Can you test if this fixes the problem in a clean R environment?

The package was bundled in the installer and it's rare for me to work in an R environment where stringr is not installed already, that is probably why I didn't spot this before.

**Comment by snsb-seifert** [comment]
App now starts without issues, 
thank you.

Fixed in 8dc7eae8049da332bb5d948ac20a724bfdd50103
