### ISSUE TITLE
Error after Install of version 0,5

### ISSUE THREAD

**Issue by Rindiser** [AgentschapPlantentuinMeise/MIDSCalculator#64]
![image](https://github.com/AgentschapPlantentuinMeise/MIDSCalculator/assets/48026710/538c8ad4-4c76-452a-af5d-cce988a0d42b)

after installing version 0,5 i get this error when trying to start the calculator

**Comment by Rindiser** [comment]
spoke too soon. Now I get:
![image](https://github.com/AgentschapPlantentuinMeise/MIDSCalculator/assets/48026710/3e4f225f-c44e-47cb-949d-58845e18539a)

and that is as far i get

**Comment by matdillen** [comment]
Fixed with ab00c19ca7c34fbce4a394193f163339bd3b2fda
